FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /agx-interface

ADD . /agx-interface

RUN yarn && yarn build:dev

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

RUN mkdir /build

COPY --from=build /agx-interface/build /build

CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]